### PR TITLE
Fix wierd scrolling

### PR DESCRIPTION
**Pull request by plastictortoise**
# Pull Request Template

## Related Issue
Weird Scrolling on large files:
image

## Changes made

Fixed it.

@BonfireScratch

### CODE REVIEW

**Comment by d-siganos** [comment]
@SimpleBinary I thought this had been fixed. Thanks!

**Comment by d-siganos** [comment]
@SimpleBinary It seems like this way, no themes are working and no text can be typed...  Could you please open a related issue describing the problem? Thanks anyways!

**Comment by d-siganos** [comment]
@SimpleBinary I have encountered this again and I believe that it is a CSS issue with the `line-height` property. Technically it should be the same, but something might have happened there. I will check on that soon.

**Comment by BonfireScratch** [comment]
@SimpleBinary have you been able to reproduce this bug in dark mode? It seems to me that it only happens in light mode.

**Comment by BonfireScratch** [comment]
@SimpleBinary turns out this is a problem with the font size of the textarea. Despite being set to the same values, the text displays smaller than it should.

**Comment by BonfireScratch** [comment]
@SimpleBinary https://jsfiddle.net/3erdab6m/ This is more or less the bug at the moment. Could you help me solve it?

**Comment by plastictortoise** [comment]
@BonfireScratch This seems to work:

EDIT: It seems to hide the cursor too. :thinking: 
```css
:root {
    --text-size: 19px;
    --indent-size: 4;
}

#src, .code-output {
    outline: 0;
    box-shadow: none;
    position: absolute;
    top: 0;
    left: 0;
    padding: 1.5rem;
    padding-left: 2rem;
    
    width: 100%;
    height: 100%;
    line-height: 1.5;
    resize: none;
    
    overflow: hidden;
    opacity: 0;
    
    -moz-tab-size: var(--indent-size);
    -o-tab-size: var(--indent-size);
    tab-size: var(--indent-size);
    -webkit-hyphens: none;
    -moz-hyphens: none;
    -ms-hyphens: none;
    hyphens: none;
    
    font-family: 'Inconsolata', monospace;
    font-size: var(--text-size);
    white-space: pre;
    word-wrap: break-word;
    text-align: left;
    
    border-top-width: 0px;
    border-top-style: solid;
    border-bottom-width: 0px;
    border-bottom-style: solid;
    margin-top: 0px;
    margin-bottom: 0px;
    border-left-width: 0px;
    border-left-style: solid;
    border-right-width: 0px;
    border-right-style: solid;
}

.code-output {
    pointer-events: none;
    z-index: 3;
    opacity: 1;
    overflow: hidden;
    background: transparent;
    text-shadow: none;
}
```

**Comment by d-siganos** [comment]
@SimpleBinary I am pushing some commits and I hope the bug is fixed. I will check frequently to see if the problem persists. I will try to answer you why the cursor is hidden in a moment...

**Comment by plastictortoise** [comment]
@BonfireScratch I've been looking into it, and it seems like this method will always hide the cursor (there is only a workaround for Safari). I feel like it would be easier to maintain with CodeFlask:

https://codepen.io/simplebinary/pen/vYNLOvM

It is quite simple to use:

```js
// How to listen for changes on your editor
flask.onUpdate((code) => {
  //...
});

// How to update your editor with custom content:
const new_content = 'let it = "go"';

flask.updateCode(new_content);
```

I think this will improve the editor in the long-term and make maintaining much easier.

**Comment by d-siganos** [comment]
@SimpleBinary I have not heard of codeflask before. I will look into it but I am trying to use the least amount of external libraries.

**Comment by d-siganos** [comment]
@SimpleBinary what I am trying to do is to, ultimately, make a completely standalone editor, with none of the main editor mechanics relying on external libraries. Therefore, I don't think I will use CodeFlask (for now). I am going to make it easier to maintain, of course, as admittedly the code needs a restructure. 

I would like to hear your opinion about the size buttons. Should they be visible by default or not? I am facing a dillema.

**Comment by plastictortoise** [comment]
@BonfireScratch I think the should be partially visible, to show the users that they exist without being too obtrusive.

**Pull request merged**
