### PR TITLE
Fix autocorrect on mobile browsers

### PR DESCRIPTION
**Pull request by plastictortoise**
# Pull Request Template

## Related Issue
Autocorrect on mobile edits tags.

## Changes made

Removed the ability to autocorrect in textarea.

### CODE REVIEW

**Comment by plastictortoise** [comment]
@BonfireScratch One More.

**Comment by plastictortoise** [comment]
@BonfireScratch Also, the code seems misalligned if you have long peices of code and you have to scroll down. This may be caused by the fact that you are applying the syntax highlighting on a seperate div and not directly on the textarea.

**Comment by d-siganos** [comment]
@SimpleBinary what do you mean by 'misalligned'? I have been trying to solve the textarea issues ever since I noticed #3, and I am making progress. However, there are many problems to fix...

**Comment by d-siganos** [comment]
@SimpleBinary I don't see what you mean, for some reason...

**Comment by d-siganos** [comment]
@SimpleBinary I now tracked the bug with an iPad, and I am pretty certain it is caused because of the font

**Comment by d-siganos** [comment]
@SimpleBinary bug is fixed now

**Pull request merged**
